version: '3.9'
services:
  postgres:
    container_name: db
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: 'Vlad211003'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'testDb'
    volumes:
      - ./src/main/resources/static/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - '6565:5432'
    restart: unless-stopped

  app:
    container_name: app
    image: eclipse-temurin
    environment:
      - CONTAINER_NAME=test
      - CONTAINER_VERSION=1.0
    working_dir: /opt/app
    volumes:
      - ./target/practicalForClearSolutions-0.0.1-SNAPSHOT.jar:/opt/app/app.jar
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - '7070:7070'
volumes:
  pgdata: